site_name: ScientificProgramming Exams
site_url: https://rflocfloc.github.io/sciprogexams/
nav:
  - Home: index.md
  - Data Science:
     - 23_11_07: 2023_11_07/ds/web_page.md
     - 23_12_19: 2023_12_19/ds/web_page.md
     - 24_01_22: 2023_12_19/ds/web_page.md
  - QCB:
     - 23_11_07: 2023_11_07/qcb/web_page.md
     - 23_12_19: 2023_12_19/qcb/web_page.md
     - 24_01_22: 2024_01_22/qcb/web_page.md
theme: readthedocs
